# Copyright 2026 Salesforce, Inc. All rights reserved.
[package]
name = "mcp_apps_policy"
version = "0.1.25"
rust-version = "1.88.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[package.metadata.anypoint]
group_id = "f684513f-280e-403a-ac53-80ca62e3de49"
definition_asset_id = "mcp-apps-policy"
implementation_asset_id = "mcp-apps-policy-impl"

[dependencies]
pdk = "1.8.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc", "preserve_order"] }
anyhow = "1.0"
thiserror = "1"

[dev-dependencies]
pdk-unit = "1.8.0"

[profile.release]
lto = true
opt-level = 'z'
strip = "debuginfo"
panic = "abort"
